### ISSUE TITLE
Ícones e título das tags disparadas para GA4

### ISSUE THREAD

**Issue by GianGP** [DP6/analytics-watcher#32]
Em alguns projetos que já tem o GA4 implementado, os eventos no analytics watcher estão aparecendo sem o nome do evento nem o ícone de evento de GA4, como abaixo:

![image](https://user-images.githubusercontent.com/66138840/198044003-152a28c5-0e1b-4345-b359-686ae23bb615.png)

Abrindo cada aba, os parâmetros estão corretos, somente o título da tag e o ícone que estão com problemas.

**Comment by diasbass** [comment]
Obrigado pelo report @GianGP.
Ajuste realizado e já funcionando na extensão.
